### ISSUE TITLE
require-relative-main + browserify

### ISSUE THREAD

**Issue by chinedufn** [bendrucker/require-relative-main#3]
Right now you can't use RRM in an app since browserify isn't shimming some of the core node depended on by RRM-required packages

**Comment by bendrucker** [comment]
Browserify is fundamentally incompatible it's doing static analysis via detective to construct the dep graph. This could be addressed via a transform that would resolve the rrm calls at bundle time.

Will close when I finish https://github.com/bendrucker/mainify
